### ISSUE TITLE
Failed starting job

### ISSUE THREAD

**Issue by arcollector** [roxma/nvim-yarp#12]
Hi, I am using your plugin because i want to use neocomplete plugin in my vim editor (not nvim), here the errors message

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/.vimrc" 184L, 4225C
[deoplete@yarp] Failed starting job: ['python3', '-u', '/home/martin/.vim/bundle
/nvim-yarp/pythonx/yarp.py', '127.0.0.1:36309', 2, 'deoplete']
[deoplete@yarp] Vim(let):E729: using Funcref as a String
[deoplete] [yarp] [deoplete] job is not running
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_i
nitialize[19]..deoplete#init#_channel[10]..yarp#core#notify[1]..yarp#core#wait_c
hannel, line 8
```
`vim --version` output
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm  
```

**Comment by roxma** [comment]
Please read the [DEBUGGING](https://github.com/roxma/nvim-yarp#debugging) section, and post the log files

**Comment by arcollector** [comment]
dont luck, my friend, maybe i missing something about how to log, can you please elaborate more on this.

BTW, i ran the command
`python3 -u /home/martin/.vim/bundle/nvim-yarp/pythonx/yarp.py 127.0.0.1:36309 2 deoplete` and this is the ouput

```
Traceback (most recent call last):
  File "/home/martin/.vim/bundle/nvim-yarp/pythonx/yarp.py", line 16, in <module>
    nvim = attach('tcp', address=serveraddr, port=port)
  File "/home/martin/.local/lib/python3.5/site-packages/neovim/__init__.py", line 100, in attach
    session = (tcp_session(address, port) if session_type == 'tcp' else
  File "/home/martin/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/__init__.py", line 27, in tcp_session
    return session('tcp', address, port)
  File "/home/martin/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/home/martin/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/home/martin/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 80, in _connect_tcp
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 695, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 682, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 402, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 432, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 36309)

```

**Comment by roxma** [comment]
> VIM - Vi IMproved 7.4 

hmm... Vim 8 is required.

To generate log fiels, simply add 

```
let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"
```

into your vimrc.

OR 

```sh
export NVIM_PYTHON_LOG_FILE=/you/log/file
export NVIM_PYTHON_LOG_LEVEL=DEBUG
/your/vim8
# now reproduce the error, and check the log files
```

**Comment by arcollector** [comment]
> hmm... Vim 8 is required.

Oups, i fell silly, i just need to update `vim`
If anyone has encountered this problem, i have solved it by running these commands

```
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim
```

thanks for you patiente, goodbye
